global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'polemica-achievement-service'
    static_configs:
      - targets: [ 'achievement-service:8081' ]
