app:
  crawl-scheduler:
    enable: true
    interval: 1h
  achievement-check-scheduler:
    enable: true
    interval: 1h
  crawlClubs:
    - 289
    - 72
    - 182
  achievement-check-game-started-after: 2024-09-26T00:00:00

spring:
  application:
    name: polemica-achievement-service
  liquibase:
    change-log: liquibase/master.xml
    enabled: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/achievement}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

#logging:
#  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
