app:
  crawl-scheduler:
    enable: true
    interval: 10m
  achievement-check-scheduler:
    enable: true
    interval: 5m
  crawlClubs:
    - 289
#    - 72
#    - 182

spring:
  application:
    name: polemica-achievement-service
  liquibase:
    change-log: liquibase/master.xml
    enabled: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/achievement}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

#logging:
#  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
