app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  link-check-properties:
    link-check-interval: 10m

spring:
  application:
    name: polemica-achievement-service
  liquibase:
    change-log: liquibase/master.xml
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/achievement
    username: postgres
    password: postgres


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

#logging:
#  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
