app:
  crawl-scheduler:
    enable: true
    interval: 10m
  achievement-check-scheduler:
    enable: true
    interval: 10m
  crawlClubs:
    - 289 # ЧХ
    - 72 # Polemica Spb
    - 182 # ВП
    - 313 # Fox
  achievement-check-game-started-after: 2000-01-01T00:00:00
  pair-statistics:
    min-games-threshold: 10
    top-partners-count: 5
    cache-enabled: true
    cache-ttl-minutes: 60


spring:
  application:
    name: polemica-achievement-service
  liquibase:
    change-log: liquibase/master.xml
    enabled: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/achievement}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
  jackson:
    default-property-inclusion: non_null


server:
  port: 8080

#logging:
#  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info, health, prometheus"
      path-mapping:
        prometheus: metrics
  retrofit:
    applicationProperty: application=${spring.application.name}
    add-application-as-prefix: true
  server:
    port: 8081
  enable:
    http.server.requests: true

