alter table games
    add column points jsonb;


-- Add OpenSkill rating fields to Users table
ALTER TABLE Users
    ADD COLUMN mu double precision;
ALTER TABLE Users
    ADD COLUMN sigma double precision;
ALTER TABLE Users
    ADD COLUMN rating double precision;
ALTER TABLE Users
    ADD COLUMN games_played int NOT NULL DEFAULT 0;
ALTER TABLE Users
    ADD COLUMN games_won int NOT NULL DEFAULT 0;

-- Create table for storing rating change history
CREATE TABLE player_rating_history
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    player_id     bigint           NOT NULL,
    game_id       bigint           NOT NULL,
    old_mu        double precision NOT NULL,
    old_sigma     double precision NOT NULL,
    new_mu        double precision NOT NULL,
    new_sigma     double precision NOT NULL,
    points_earned double precision NOT NULL,
    is_win        boolean          NOT NULL,
    mu_delta      double precision NOT NULL,
    weight        double precision NOT NULL,
    match_quality double precision NOT NULL,
    timestamp     timestamp        NOT NULL,

    CONSTRAINT pk_player_rating_history PRIMARY KEY (id),
    CONSTRAINT fk_rating_history_user FOREIGN KEY (player_id) REFERENCES Users (user_id)
);

-- Create indices for faster queries
CREATE INDEX idx_rating_history_player ON player_rating_history (player_id);
CREATE INDEX idx_rating_history_game ON player_rating_history (game_id);
