CREATE TABLE recalibration_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id   BIGINT                                  NOT NULL,
    game_id     BIGINT                                  NOT NULL,
    game_number INTEGER                                 NOT NULL,
    old_sigma   DOUBLE PRECISION                        NOT NULL,
    new_sigma   DOUBLE PRECISION                        NOT NULL,
    reason      VARCHAR(255)                            NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_recalibration_history PRIMARY KEY (id)
);

ALTER TABLE recalibration_history
    ADD CONSTRAINT FK_RECALIBRATION_HISTORY_ON_PLAYER FOREIGN KEY (player_id) REFERENCES users (user_id);
